import pygame

# debug
RENDER_BBS = False

# camera
GAME_CAM_HEIGHT = 240
GAME_CAM_WIDTH = GAME_CAM_HEIGHT // 9 * 16


# cards
CARD_START_X = 0
CARD_START_Y = 0

CARD_Y_POS_BASE = GAME_CAM_HEIGHT * 11 / 12
CARD_Y_POS_SELECTING = -10
CARD_Y_POS_SELECTED = -14
CARD_X_FIX_DISTANCE = 50

CARD_ANIMATION_SPEED = 4.0

CARD_WIDTH: float = 62.0
CARD_HEIGHT: float = 88.0
RELATIVE_MARKER_POS_X = 4
RELATIVE_MARKER_POS_Y = 13
CARD_TITLE_TEXT_RELATIVE_POS_X = 4
CARD_TITLE_TEXT_RELATIVE_POS_Y = 4

MAX_CARD_COUNT = 10

# map
SEED = None

ISO_MAP_HEIGHT = 8
ISO_MAP_WIDTH = 8

ISO_TILE_OFFSET_X = 16
ISO_TILE_OFFSET_Y = ISO_TILE_OFFSET_X // 2
ISO_POS_OFFSET_X = (
    GAME_CAM_WIDTH // 2 - ISO_TILE_OFFSET_X * (ISO_MAP_WIDTH + ISO_MAP_HEIGHT) // 2
)
ISO_POS_OFFSET_Y = (CARD_Y_POS_BASE + CARD_Y_POS_SELECTED) / 2 - ISO_TILE_OFFSET_Y * (
    ISO_MAP_HEIGHT + ISO_MAP_WIDTH
) / 8

ISO_TILE_SELECT_OFFSET = -2

# UI
FONT_COLOR = pygame.Color(53, 43, 66, 255)
FONT_SIZE = 6

BUTTON_WIDTH = 64
BUTTON_HEIGHT = 13
