from math import sqrt

ROOT_TWO = sqrt(2.0)

# camera
GAME_CAM_HEIGHT = 144
GAME_CAM_WIDTH = GAME_CAM_HEIGHT // 9 * 16
PIXEL_SIZE = 1080 / GAME_CAM_HEIGHT


# cards
CARD_START_X = 0
CARD_START_Y = 0

CARD_Y_POS_BASE = 130
CARD_Y_POS_SELECTING = 125
CARD_Y_POS_SELECTED = 120
CARD_ROTATION_PER_CARD = 6

CARD_ANIMATION_SPEED = 4.0

CARD_WIDTH: float = 31.0
CARD_HEIGHT: float = 44.0
RELATIVE_MARKER_POS_X = 2
RELATIVE_MARKER_POS_Y = 2

MAX_CARD_COUNT = 10

# map
SEED = None

ISO_MAP_HEIGHT = 6
ISO_MAP_WIDTH = 6

ISO_TILE_OFFSET_X = 8
ISO_TILE_OFFSET_Y = ISO_TILE_OFFSET_X // 2
ISO_POS_OFFSET_X = (
    GAME_CAM_WIDTH // 2 - ISO_TILE_OFFSET_X * (ISO_MAP_WIDTH + ISO_MAP_HEIGHT) // 2
)
ISO_POS_OFFSET_Y = 50
