from dataclasses import dataclass

from .colors import ColorEnum


@dataclass
class Settings:
    # debug
    RENDER_BBS = False
    RENDER_PERLIN_HEIGHT = False
    RENDER_MASKS_OUT = False
    RENDER_MASKS_IN = False

    # Logging
    LOG_TICK_PERFORMANCE = False
    LOG_ASSET_LOADING = True
    LOG_SPAWNING = False
    LOG_PLAY_SOUND = False

    # rendering
    GAME_CAM_HEIGHT = 270
    GAME_CAM_WIDTH = GAME_CAM_HEIGHT // 9 * 16

    GAME_FULLSCREEN = True
    GAME_MUTE = True

    FPS = 600

    # audio
    GAME_MUTE = True
    MASTER_VOLUME: float = 1.0

    # defaults
    DEFAULT_RESOURCE_MANA = 99
    DEFAULT_RESOURCE_HERBS = 99
    DEFAULT_RESOURCE_BLOOD = 99
    DEFAULT_RESOURCE_BREW = 99

    STARTER_DECK_COUNT = 30
    # cards
    CARD_START_X = 0
    CARD_START_Y = 0

    CARD_Y_POS_BASE = GAME_CAM_HEIGHT * 11 // 12
    CARD_Y_POS_SELECTING = -15
    CARD_Y_POS_SELECTED = -30
    CARD_X_FIX_DISTANCE = GAME_CAM_HEIGHT // 5

    CARD_ANIMATION_SPEED = 70

    CARD_WIDTH = 80
    CARD_HEIGHT = 110

    RELATIVE_MARKER_POS_X = 2
    RELATIVE_MARKER_POS_Y = 11
    MARKER_OFFSET_X = 8

    CARD_TEXT_RELATIVE_POS_X = CARD_WIDTH // 2
    CARD_TITLE_TEXT_RELATIVE_POS_Y = 6
    CARD_PARAGRAPH_TEXT_RELATIVE_Y_ONE = CARD_HEIGHT // 2 + 10
    CARD_PARAGRAPH_TEXT_RELATIVE_Y_OFFSET = 6
    CARD_PARAGRAPH_LETTER_COUNT = 15
    CARD_PARAGRAPH_LINE_COUNT = 4

    MAX_CARD_COUNT = 10

    # perlin
    NOISE_SEED = 1013
    NOISE_LAYERS = 5
    NOISE_SCALE = 0.5
    NOISE_ROUGHNESS = 8
    NOISE_PERISITANCE = 0.2
    NOISE_THRESHOLDS = [0.4, 0.6, 0.8, 1.0]

    ISO_MAP_HEIGHT = 9
    ISO_MAP_WIDTH = 9

    ISO_TILE_SPRITE_HEIGHT = 64
    ISO_TILE_SPRITE_WIDTH = 32
    ISO_TILE_OFFSET_X = ISO_TILE_SPRITE_WIDTH // 2
    ISO_TILE_OFFSET_Y = ISO_TILE_OFFSET_X // 2
    ISO_POS_OFFSET_X = (
        GAME_CAM_WIDTH // 2
        - ISO_TILE_OFFSET_X * (ISO_MAP_WIDTH + ISO_MAP_HEIGHT) // 2
    )
    ISO_POS_OFFSET_Y = (
        (CARD_Y_POS_BASE + CARD_Y_POS_SELECTED) // 2
        - ISO_TILE_OFFSET_Y * (ISO_MAP_HEIGHT - ISO_MAP_WIDTH) // 2
        - 20
    )

    ISO_TILE_SELECT_OFFSET = -2
    ISO_ACTIVE_TILE_SELECT_OFFSET = -1
    ISO_HEIGHT_MAX_OFFSET = 10
    ISO_HEIGHT_MIN_OFFSET = -10

    ISO_KNIGHT_SPAWN_CHANCE = 0
    ISO_FARMER_SPAWN_CHANCE = 5
    ISO_SPAWN_CHANCE_MAX = 100

    ISO_TARGET_CUTOFF = 4
    ISO_RANGED_ARCH = 60

    # UI
    FONT_COLOR = ColorEnum.SHADE_DARK.value
    FONT_SIZE = 16

    BUTTON_TILE_SIZE = 12


SETTINGS_REF = Settings()
